### ISSUE TITLE
Design branded report

### ISSUE THREAD

**Issue by cindydevelvis** [cindydevelvis/miamimba#6]

**Comment by cindydevelvis** [comment]
View mockup of branded report here: 
![image](https://cloud.githubusercontent.com/assets/14876080/17315811/b1f5d02e-583c-11e6-8ec8-99c141964397.png)

**Comment by cindydevelvis** [comment]
Hi @RFGJanice I have the first draft ready to review here: https://www.dropbox.com/sh/8zi4ful3vz9j06w/AABJJ5vECmj6-Lns0AUn

Please let me know your thoughts.

**Comment by RFGJanice** [comment]
Thanks @cindydevelvis this is a great start. Just a few tweaks and we'll be there:
- [x] Make the logo bigger and ensure proper clear space
- [x] The chart is getting really crowded. Can we eliminate a few measures to make it easier to read and understand at a glance?
- [ ] Can we add a countdown to deadline?

**Comment by cindydevelvis** [comment]
@RFGJanice Great suggestions. I've made it through the first two items, working on the countdown. Can you provide more clarity on what you envision? A number callout, calendar, clock, etc.? We may want to schedule a quick 15 minute Skype to talk through ideas.
